<?php

declare(strict_types=1);

namespace GruffPhp\Command;

use GruffPhp\Config\AnalysisConfig;
use GruffPhp\Config\ConfigLoader;
use GruffPhp\Config\SeverityThreshold;
use GruffPhp\Rule\RuleDefinition;
use GruffPhp\Rule\RuleRegistry;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Yaml;

/**
 * Writes a default gruff-php YAML config file derived from the rule registry.
 */
final class InitCommand extends Command
{
    /**
     * Header inserted at the top of generated config files.
     */
    private const FILE_HEADER = "# .gruff-php.yaml\n"
        . "# Generated by `gruff-php init`. Mirrors gruff-php registry defaults; edit to customise.\n"
        . "# Add project-specific generated paths under paths.ignore, such as var/cache/** or generated/**.\n"
        . "# After reviewing current findings, `gruff-php analyse --generate-baseline` records them as known debt.\n"
        . "# Future analyse/report runs auto-apply gruff-baseline.json; use `gruff-php analyse --no-baseline` to audit without it.\n";

    /**
     * Inline depth used when dumping the YAML document.
     *
     * Keeps every list value (e.g. allowedLiterals) on its own line.
     */
    private const YAML_INLINE_DEPTH = 10;

    /**
     * Indent width matching the existing project config files.
     */
    private const YAML_INDENT = 4;

    /**
     * Default paths omitted from generated project scans.
     *
     * Keeps agent harness files, generated reports, copied vendor code, and
     * analyzer fixtures out of normal user-facing reports.
     *
     * @var list<string>
     */
    private const DEFAULT_IGNORED_PATHS = [
        '.agents/**',
        '.antigravitycli/**',
        '.claude/**',
        '.codex/**',
        '.github/**',
        '.goat-flow/**',
        'history.json',
        'infection-report.json',
        'src/Vendor/**',
        'tests/Fixtures/**',
    ];

    /**
     * Universal-programming abbreviations seeded into fresh configs so the
     * first scan does not flood naming.abbreviation-allowlist with terms a
     * maintainer would never bother to allowlist by hand. Project-specific
     * vocabulary (domain acronyms) should be appended to this list in the
     * user's config rather than added here.
     *
     * @var list<string>
     */
    private const DEFAULT_ACCEPTED_ABBREVIATIONS = [
        'age', 'app', 'db', 'fs', 'id', 'io', 'key', 'log', 'max', 'min', 'now', 'raw', 'rx', 'tx', 'ui', 'url',
    ];

    /**
     * Register init CLI options and metadata.
     *
     * @return void
     */
    protected function configure(): void
    {
        $this
            ->setName('init')
            ->setDescription('Write a default .gruff-php.yaml config file populated with registry defaults.')
            ->addOption('project-root', null, InputOption::VALUE_REQUIRED, 'Directory to write the config file in. Defaults to the current working directory.')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Overwrite an existing .gruff-php.yaml file or write alongside a legacy .gruff.yaml.');
    }

    /**
     * Generate the default config file at the project root.
     *
     * @return int Symfony command exit code.
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $projectRoot = $this->projectRoot($input, $output);
        if ($projectRoot === null) {
            return Command::FAILURE;
        }

        $targetPath  = $projectRoot . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;
        $shouldForce = (bool) $input->getOption('force');

        $guardExitCode = $this->guardExistingConfig($projectRoot, $targetPath, $shouldForce, $output);
        if ($guardExitCode !== null) {
            return $guardExitCode;
        }

        $registry = RuleRegistry::defaults();
        $config   = AnalysisConfig::fromRegistry($registry);

        $ignoredPaths = self::existingIgnoredPaths($targetPath) ?? self::DEFAULT_IGNORED_PATHS;
        $scaffold     = self::buildScaffoldDocument($config, $ignoredPaths);
        $scaffoldYaml = Yaml::dump($scaffold, self::YAML_INLINE_DEPTH, self::YAML_INDENT, Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);
        $rulesYaml    = self::renderRulesSection($registry);
        $contents     = self::FILE_HEADER . $scaffoldYaml . $rulesYaml;

        if (file_put_contents($targetPath, $contents) === false) {
            $output->writeln(sprintf('<error>Unable to write %s.</error>', $targetPath));

            return Command::FAILURE;
        }

        $output->writeln(sprintf('Wrote %s', $targetPath));
        $output->writeln('');
        $output->writeln('Next steps:');
        $output->writeln('  1. Edit paths.ignore for project-local generated files.');
        $output->writeln('  2. Run `gruff-php summary` to review the current finding mix.');
        $output->writeln('  3. Optional after review: `gruff-php analyse --generate-baseline` records current findings as known debt.');
        $output->writeln('     Use `gruff-php analyse --no-baseline` to audit without that baseline.');

        return Command::SUCCESS;
    }

    /**
     * Resolve the directory the new config file will be written to.
     *
     * @return string|null Directory to use, or null after emitting an error.
     */
    private function projectRoot(InputInterface $input, OutputInterface $output): ?string
    {
        $explicit = $input->getOption('project-root');
        if (is_string($explicit) && $explicit !== '') {
            if (!is_dir($explicit)) {
                $output->writeln(sprintf('<error>--project-root must be an existing directory: %s</error>', $explicit));

                return null;
            }

            return rtrim($explicit, '/');
        }

        $cwd = getcwd();
        if ($cwd === false) {
            $output->writeln('<error>Unable to determine current working directory.</error>');

            return null;
        }

        return $cwd;
    }

    /**
     * Refuse to overwrite a preferred or legacy config file without --force.
     *
     * @return int|null Exit code when init must refuse, or null when writing may proceed.
     */
    private function guardExistingConfig(string $projectRoot, string $targetPath, bool $shouldForce, OutputInterface $output): ?int
    {
        if ($shouldForce) {
            return null;
        }

        if (is_file($targetPath)) {
            $output->writeln(sprintf(
                '<error>%s already exists. Pass --force to overwrite.</error>',
                ConfigLoader::DEFAULT_CONFIG_FILE,
            ));

            return Command::FAILURE;
        }

        $legacyPath = $projectRoot . '/' . ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE;
        if (is_file($legacyPath)) {
            $output->writeln(sprintf(
                '<error>%s already exists; writing %s would silently switch analyse over to generated defaults. Remove or rename the legacy file, or pass --force to write the preferred config alongside it.</error>',
                ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE,
                ConfigLoader::DEFAULT_CONFIG_FILE,
            ));

            return Command::FAILURE;
        }

        return null;
    }

    /**
     * Build the scaffold sections of the generated config (everything above
     * `rules:`). The `rules:` block is rendered separately by
     * renderRulesSection so each rule can carry a leading description comment
     * that Yaml::dump can't emit.
     *
     * @param AnalysisConfig $analysisConfig Config seeded from the registry defaults.
     * @param list<string>   $ignoredPaths Paths to omit from generated project scans.
     * @return array<string, mixed>
     */
    private static function buildScaffoldDocument(AnalysisConfig $analysisConfig, array $ignoredPaths): array
    {
        return [
            'minimumPhpVersion' => $analysisConfig->minimumPhpVersion(),
            'paths' => [
                'ignore' => $ignoredPaths,
            ],
            'allowlists' => [
                'acceptedAbbreviations' => self::DEFAULT_ACCEPTED_ABBREVIATIONS,
                'secretPreviews' => [],
            ],
            'selection' => [
                'tiers' => [],
                'pillars' => [],
                'rules' => [],
                'excludePillars' => [],
                'excludeRules' => [],
            ],
        ];
    }

    /**
     * Render the `rules:` section of the generated config, with each rule
     * preceded by a comment carrying the registry description (or the rule's
     * display name when no description is set). Output is appended to the
     * scaffold YAML; the existing 4-space indent contract is preserved.
     *
     * @return string Rendered `rules:` block including trailing newline.
     */
    private static function renderRulesSection(RuleRegistry $ruleRegistry): string
    {
        $output = "rules:\n";
        foreach ($ruleRegistry->all() as $rule) {
            $ruleDefinition = $rule->definition();
            $description    = $ruleDefinition->description !== '' ? $ruleDefinition->description : $ruleDefinition->name;
            $output        .= '    # ' . $description . "\n";
            $entry          = self::buildRuleEntry($ruleDefinition);
            $entryYaml      = Yaml::dump([$ruleDefinition->id => $entry], self::YAML_INLINE_DEPTH, self::YAML_INDENT, Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);
            foreach (explode("\n", rtrim($entryYaml, "\n")) as $line) {
                $output .= '    ' . $line . "\n";
            }
        }

        return $output;
    }

    /**
     * Read an existing config's path ignores so --force does not wipe local policy.
     *
     * @return list<string>|null Existing ignore paths, or null when none can be preserved.
     */
    private static function existingIgnoredPaths(string $targetPath): ?array
    {
        if (!is_file($targetPath)) {
            return null;
        }

        try {
            $decoded = Yaml::parseFile($targetPath);
        } catch (ParseException) {
            return null;
        }

        if (!is_array($decoded)) {
            return null;
        }

        $paths = $decoded['paths'] ?? null;
        if (!is_array($paths)) {
            return null;
        }

        $ignore = $paths['ignore'] ?? null;
        if (!is_array($ignore) || !array_is_list($ignore)) {
            return null;
        }

        $ignoredPaths = [];
        foreach ($ignore as $path) {
            if (!is_string($path) || trim($path) === '') {
                return null;
            }

            $ignoredPaths[] = trim($path);
        }

        return $ignoredPaths;
    }

    /**
     * Serialise one rule's registry defaults into the config shape.
     *
     * @param RuleDefinition $ruleDefinition Rule definition to serialise.
     * @return array<string, mixed>
     */
    private static function buildRuleEntry(RuleDefinition $ruleDefinition): array
    {
        $ruleEntry = ['enabled' => $ruleDefinition->isEnabledByDefault];

        if ($ruleDefinition->severityThreshold instanceof SeverityThreshold) {
            $ruleEntry['threshold'] = $ruleDefinition->severityThreshold->threshold;
            $ruleEntry['severity']  = $ruleDefinition->severityThreshold->severity->value;
        }

        if ($ruleDefinition->defaultThresholds !== []) {
            $ruleEntry['thresholds'] = $ruleDefinition->defaultThresholds;
        }

        if ($ruleDefinition->defaultOptions !== []) {
            $ruleEntry['options'] = $ruleDefinition->defaultOptions;
        }

        return $ruleEntry;
    }
}
