<?php

declare(strict_types=1);

namespace GruffPhp\Cli\Command;

use GruffPhp\Engine\Config\AnalysisConfig;
use GruffPhp\Engine\Config\ConfigException;
use GruffPhp\Engine\Config\ConfigLoader;
use GruffPhp\Engine\Config\SeverityThreshold;
use GruffPhp\Output\Reporter\FailThreshold;
use GruffPhp\Rules\Contracts\RuleDefinition;
use GruffPhp\Rules\RuleRegistry;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Yaml;

/**
 * Backs the `gruff-php init` command - the one-time scaffolder that writes a starter
 * `.gruff-php.yaml` populated with the current rule registry defaults.
 *
 * Reach for this the first time a project has no config and the user wants a real file to
 * edit instead of leaning on invisible built-in defaults: it mirrors every registered rule
 * with a description comment, seeds sensible path ignores and gating thresholds, and refuses
 * to clobber an existing config without `--force`. On a forced rerun it carries any
 * hand-edited `minimumSeverity:` and `paths.ignore` blocks forward, so local policy survives.
 */
final class InitCommand extends Command
{
    /**
     * Comment banner written at the very top of the generated file, so the first thing the user
     * sees on opening `.gruff-php.yaml` explains where it came from and how to extend it.
     */
    private const FILE_HEADER = "# .gruff-php.yaml\n"
                                . "# Generated by `gruff-php init`. Mirrors gruff-php registry defaults; edit to customise.\n"
                                . "# Add project-specific generated paths under paths.ignore, such as var/cache/** or generated/**.\n"
                                . "# After reviewing current findings, `gruff-php analyse --generate-baseline` records them as known debt.\n"
                                . "# Future analyse/report runs auto-apply gruff-baseline.json; use `gruff-php analyse --no-baseline` to audit without it.\n";

    /**
     * The generated `sensitiveExclusions:` block. Rendered by hand rather than through `Yaml::dump`
     * so the user meets the rules of the section - authored by hand, one reviewed scope per entry,
     * a mandatory rationale - in the file itself. gruff never writes an entry for the user, and no
     * reported preview, message, or value is ever convertible into one: an entry names a rule and a
     * path, never anything about the matched secret.
     */
    private const SENSITIVE_EXCLUSIONS_SECTION = "# Sensitive-data findings are suppressed only here, and only by hand.\n"
                                                 . "# gruff never converts a reported finding, message, or preview value into an entry for you.\n"
                                                 . "# Each entry needs one exact sensitive-data rule id, one project-relative path, and a reason;\n"
                                                 . "# an optional `symbol` narrows it further. Nothing else is suppressed - the same rule in another\n"
                                                 . "# file and another rule in the same file both keep reporting.\n"
                                                 . "# Every entry is published in the report's `suppressions` array with the count it hid, so an entry\n"
                                                 . "# that matches nothing simply reports `suppressed: 0` instead of failing the run.\n"
                                                 . "#\n"
                                                 . "# sensitiveExclusions:\n"
                                                 . "#     - rule: sensitive-data.aws-access-key\n"
                                                 . "#       path: tests/Fixtures/SensitiveData/synthetic-secrets.php\n"
                                                 . "#       reason: Synthetic key used by the scanner fixtures; not a live credential.\n"
                                                 . "sensitiveExclusions: []\n";

    /**
     * How deep `Yaml::dump` expands maps and lists before collapsing them to inline `{}`/`[]`.
     * Set high so every list value (e.g. `allowedLiterals`) lands on its own line, keeping the
     * generated file diffable and easy for the user to hand-edit afterwards.
     */
    private const YAML_INLINE_DEPTH = 10;

    /**
     * Indent width for the dumped YAML, matched to the existing project config files so a
     * regenerated document lines up with anything the user already committed.
     */
    private const YAML_INDENT = 4;

    /**
     * Default `minimumSeverity:` block written into a fresh config. Gating starts at "show
     * everything, fail on anything" for `analyse` and stays off for the read-only viewing
     * commands (`report`, `dashboard`), so a new project fails CI on any finding until the user
     * deliberately relaxes it. A hand-edited block survives `--force` via `existingMinimumSeverity`.
     *
     * @var array<string, string>
     */
    private const DEFAULT_MINIMUM_SEVERITY = [
        'analyse' => 'advisory',
        'report' => 'none',
        'dashboard' => 'none',
    ];

    /**
     * Path globs seeded into `paths.ignore` for a fresh config. Keeps agent harness files,
     * generated reports, copied vendor code, and analyzer fixtures out of the scans a user runs
     * day to day, so their findings reflect code they actually own.
     *
     * @var list<string>
     */
    private const DEFAULT_IGNORED_PATHS = [
        '.agents/**',
        '.antigravitycli/**',
        '.claude/**',
        '.codex/**',
        '.github/**',
        '.goat-flow/**',
        'history.json',
        'infection-report.json',
        'src/Vendor/**',
        'tests/Fixtures/**',
    ];

    /**
     * Universal-programming abbreviations seeded into fresh configs. Sourced from
     * `AnalysisConfig::DEFAULT_ACCEPTED_ABBREVIATIONS` so the runtime default and the
     * scaffolded init file stay in lockstep; the constant lives on `AnalysisConfig` because
     * the runtime default is the source of truth and init is just a reflection of it.
     *
     * @var list<string>
     */
    private const DEFAULT_ACCEPTED_ABBREVIATIONS = AnalysisConfig::DEFAULT_ACCEPTED_ABBREVIATIONS;

    /**
     * Declares the `init` command's name, description, and the two flags a user can pass
     * (`--project-root` and `--force`) so Symfony can route the command and `--help` can list them.
     *
     * @return void - Nothing; the command definition is registered on this instance as a side effect.
     */
    protected function configure(): void
    {
        $this
            ->setName('init')
            ->setDescription('Write a default .gruff-php.yaml config file populated with registry defaults.')
            ->addOption('project-root', null, InputOption::VALUE_REQUIRED, 'Directory to write the config file in. Defaults to the current working directory.')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Overwrite an existing .gruff-php.yaml file or write alongside a legacy .gruff.yaml.');
    }

    /**
     * Runs the whole command when a user types `gruff-php init`: pick the target directory, refuse
     * to clobber an existing config, then render the registry defaults to `.gruff-php.yaml` and
     * print the wrote-path plus next-steps guidance.
     *
     * @param InputInterface  $input  - Console input; only the `--project-root` and `--force` options are read.
     * @param OutputInterface $output - Console output; carries the wrote-path notice, next-steps guidance, and any error.
     *
     * @return int - Symfony command exit code; SUCCESS after writing, FAILURE on a bad directory, existing file, or write error.
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $projectRoot = $this->projectRoot($input, $output);
        // No usable target directory (a bad `--project-root` or an unreadable working directory); the error is already shown.
        if ($projectRoot === null) {
            return Command::FAILURE;
        }

        $targetPath  = $projectRoot . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;
        $shouldForce = (bool)$input->getOption('force');

        $guardExitCode = $this->guardExistingConfig($projectRoot, $targetPath, $shouldForce, $output);
        // A config already sits here (or a legacy file would be shadowed) and `--force` was absent; stop with its verdict.
        if ($guardExitCode !== null) {
            return $guardExitCode;
        }

        $registry = RuleRegistry::defaults();
        $config   = AnalysisConfig::fromRegistry($registry);

        // Reuse the user's existing ignore list when the file already has one; otherwise seed the shipped defaults.
        $ignoredPaths = self::existingIgnoredPaths($targetPath) ?? self::DEFAULT_IGNORED_PATHS;

        // Carry forward any gating threshold the user hand-edited, and validate their schema version (an incompatible one throws below) before regenerating over the file.
        try {
            $minimumSeverity = self::existingMinimumSeverity($targetPath) ?? self::DEFAULT_MINIMUM_SEVERITY;
            self::existingSchemaVersion($targetPath);
        } catch (ConfigException $exception) {
            // Their existing config carries an invalid block; surface why and refuse rather than overwrite it blindly.
            $output->writeln(sprintf('<error>%s</error>', $exception->getMessage()));

            return Command::FAILURE;
        }

        $scaffold     = self::buildScaffoldDocument($config, $ignoredPaths, $minimumSeverity);
        $scaffoldYaml = Yaml::dump($scaffold, self::YAML_INLINE_DEPTH, self::YAML_INDENT, Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);
        $rulesYaml    = self::renderRulesSection($registry);
        $contents     = self::FILE_HEADER . $scaffoldYaml . self::SENSITIVE_EXCLUSIONS_SECTION . $rulesYaml;

        // The write itself failed (unwritable directory or a full disk); tell the user rather than claim success.
        if (file_put_contents($targetPath, $contents) === false) {
            $output->writeln(sprintf('<error>Unable to write %s.</error>', $targetPath));

            return Command::FAILURE;
        }

        $output->writeln(sprintf('Wrote %s', $targetPath));
        $output->writeln('');
        $output->writeln('Next steps:');
        $output->writeln('  1. Edit paths.ignore for project-local generated files.');
        $output->writeln('  2. Run `gruff-php summary` to review the current finding mix.');
        $output->writeln('  3. Optional after review: `gruff-php analyse --generate-baseline` records current findings as known debt.');
        $output->writeln('     Use `gruff-php analyse --no-baseline` to audit without that baseline.');

        return Command::SUCCESS;
    }

    /**
     * Decides where the config file lands: an explicit `--project-root` wins, otherwise the
     * directory the user launched from. Runs first so every later path is anchored to one root.
     *
     * @param InputInterface  $input  - Console input; an explicit `--project-root` wins, else the current working directory is used.
     * @param OutputInterface $output - Console output used to report a missing directory or an undeterminable working directory.
     *
     * @return string|null - Directory to write into; null when the directory is missing or the cwd is unreadable, which aborts init.
     */
    private function projectRoot(InputInterface $input, OutputInterface $output): ?string
    {
        $explicit = $input->getOption('project-root');
        // The user named a directory with `--project-root` (e.g. `gruff-php init --project-root ./app`); honour it.
        if (is_string($explicit) && $explicit !== '') {
            // Reject a `--project-root` that isn't a real directory (a typo like `./ap`) before writing anything.
            if (!is_dir($explicit)) {
                $output->writeln(sprintf('<error>--project-root must be an existing directory: %s</error>', $explicit));

                return null;
            }

            return rtrim($explicit, '/');
        }

        $cwd = getcwd();
        // No `--project-root`, so fall back to the launch directory; getcwd() fails only when it was deleted or unreadable.
        if ($cwd === false) {
            $output->writeln('<error>Unable to determine current working directory.</error>');

            return null;
        }

        return $cwd;
    }

    /**
     * Stops init from silently destroying work: refuses when a `.gruff-php.yaml` already exists, or
     * when a legacy `.gruff.yaml` sits alongside that a new file would quietly override. Runs before
     * any content is generated, so the user is warned while their files are still intact.
     *
     * @param string          $projectRoot - Directory checked for a sibling legacy `.gruff.yaml` that `--force` would shadow.
     * @param string          $targetPath  - Full path of the `.gruff-php.yaml` about to be written; refused when it already exists.
     * @param bool            $shouldForce - True bypasses both guards; the caller derives it from the `--force` option.
     * @param OutputInterface $output      - Console output used to explain why init refused.
     *
     * @return int|null - Exit code when init must refuse and stop; null when nothing is in the way and writing may proceed.
     */
    private function guardExistingConfig(string $projectRoot, string $targetPath, bool $shouldForce, OutputInterface $output): ?int
    {
        // The user passed `--force`, opting into overwriting; skip both guards and let the write proceed.
        if ($shouldForce) {
            return null;
        }

        // The user reran `gruff-php init` where a config already exists without `--force`; refuse rather than wipe their edits.
        if (is_file($targetPath)) {
            $output->writeln(sprintf(
                                 '<error>%s already exists. Pass --force to overwrite.</error>',
                                 ConfigLoader::DEFAULT_CONFIG_FILE,
                             ));

            return Command::FAILURE;
        }

        $legacyPath = $projectRoot . '/' . ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE;
        // An old-style `.gruff.yaml` is present; writing the preferred `.gruff-php.yaml` would silently switch analyse onto that new file (it loads ahead of the legacy one), so warn.
        if (is_file($legacyPath)) {
            $output->writeln(sprintf(
                                 '<error>%s already exists; writing %s would silently switch analyse over to generated defaults. Remove or rename the legacy file, or pass --force to write the preferred config alongside it.</error>',
                                 ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE,
                                 ConfigLoader::DEFAULT_CONFIG_FILE,
                             ));

            return Command::FAILURE;
        }

        return null;
    }

    /**
     * Assembles everything above the `rules:` block of the generated config - schema version,
     * minimum PHP version, severity gating, ignore paths, allowlists, and selection stubs - in the
     * exact order init emits them. The `rules:` block is rendered separately so each rule can carry
     * a description comment that `Yaml::dump` cannot emit.
     *
     * @param AnalysisConfig        $analysisConfig  - Config seeded from the registry defaults.
     * @param list<string>          $ignoredPaths    - Paths to omit from generated project scans; these are what the user tunes after init.
     * @param array<string, string> $minimumSeverity - Per-command exit-code thresholds emitted under `minimumSeverity:`.
     *
     * @return array<string, mixed> - Scaffold document keyed in the exact order init emits above the rules block, ready for `Yaml::dump`.
     */
    private static function buildScaffoldDocument(AnalysisConfig $analysisConfig, array $ignoredPaths, array $minimumSeverity): array
    {
        return [
            'schemaVersion' => ConfigLoader::SCHEMA_VERSION,
            'minimumPhpVersion' => $analysisConfig->minimumPhpVersion(),
            'deepScanBudget' => [
                'enabled' => $analysisConfig->deepScanBudget()['enabled'],
                'maxLines' => $analysisConfig->deepScanBudget()['maxLines'],
                'maxBytes' => $analysisConfig->deepScanBudget()['maxBytes'],
            ],
            'minimumSeverity' => $minimumSeverity,
            'paths' => [
                'ignore' => $ignoredPaths,
            ],
            'allowlists' => [
                'acceptedAbbreviations' => self::DEFAULT_ACCEPTED_ABBREVIATIONS,
                'secretPreviews' => [],
            ],
            'selection' => [
                'tiers' => [],
                'pillars' => [],
                'rules' => [],
                'excludePillars' => [],
                'excludeRules' => [],
            ],
        ];
    }

    /**
     * Renders the `rules:` block by hand so each rule can be preceded by a comment carrying its
     * registry description - the annotations that tell the user what a rule checks when they open
     * the file (falling back to the rule's display name when it ships without a description).
     * Appended after the scaffold YAML, preserving the existing 4-space indent contract.
     *
     * @param RuleRegistry $ruleRegistry - Source of the rules to render and the descriptions that become their comments.
     *
     * @return string - Rendered `rules:` block including trailing newline.
     */
    private static function renderRulesSection(RuleRegistry $ruleRegistry): string
    {
        $output = "rules:\n";
        // Walk every registered rule so the generated file lists them all, each under its own description comment.
        foreach ($ruleRegistry->all() as $rule) {
            $ruleDefinition = $rule->definition();
            // Prefer the rule's written description; fall back to its display name when it ships without one.
            $description = $ruleDefinition->description !== '' ? $ruleDefinition->description : $ruleDefinition->name;
            $output .= '    # ' . $description . "\n";
            $ruleEntry     = self::buildRuleEntry($ruleDefinition);
            $ruleEntryYaml = Yaml::dump([$ruleDefinition->id => $ruleEntry], self::YAML_INLINE_DEPTH, self::YAML_INDENT, Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);
            // Re-indent each dumped line by four spaces so the rule nests correctly under the `rules:` key.
            foreach (explode("\n", rtrim($ruleEntryYaml, "\n")) as $line) {
                $output .= '    ' . $line . "\n";
            }
        }

        return $output;
    }

    /**
     * Reads an existing config's `minimumSeverity:` block so a `--force` rerun carries the user's
     * hand-edited gating thresholds forward instead of resetting them. Validates each entry the same
     * way the loader does, so a broken block errors out rather than being silently kept.
     *
     * @param string $targetPath - Path of the config file being regenerated, read for a hand-edited block to carry forward.
     *
     * @return array<string, string>|null - Existing block (command => threshold); null when there's no block to preserve, so defaults apply.
     * @throws ConfigException When a preserved entry is not a valid gating command or threshold value.
     */
    private static function existingMinimumSeverity(string $targetPath): ?array
    {
        // No existing block to carry forward (fresh file or no such key); signal "use the defaults" with null.
        if (!self::hasMinimumSeverityBlock($targetPath)) {
            return null;
        }

        $existing  = self::readMinimumSeverityBlock($targetPath);
        $preserved = [];
        // Validate each preserved entry, so a typo'd command or threshold stops init instead of riding along.
        foreach ($existing as $command => $threshold) {
            $preserved[self::validateGatingCommand($command)] = self::validateGatingThreshold((string)$command, $threshold);
        }

        return $preserved;
    }

    /**
     * Reports whether the existing config carries a top-level `minimumSeverity:` key worth
     * preserving. Split from {@see readMinimumSeverityBlock} so the pair never returns a nullable
     * mixed-array shape from one helper, which would trip `modernisation.phpdoc-mixed-overuse`.
     *
     * @param string $targetPath - Path of the existing config file to probe; a missing or unparseable file counts as absent.
     *
     * @return bool - True when the YAML loads and contains a top-level `minimumSeverity:` key; false otherwise.
     */
    private static function hasMinimumSeverityBlock(string $targetPath): bool
    {
        // Nothing on disk yet (first-time init), so there is no block to preserve.
        if (!is_file($targetPath)) {
            return false;
        }

        try {
            $decoded = Yaml::parseFile($targetPath);
        } catch (ParseException) {
            // The file is present but not valid YAML; treat it as having no preservable block rather than crashing.
            return false;
        }

        // A block exists only when the document parsed to a map that actually holds the `minimumSeverity` key.
        return is_array($decoded) && array_key_exists('minimumSeverity', $decoded);
    }

    /**
     * Pulls the raw `minimumSeverity:` map out of the existing config and checks only its overall
     * shape; the caller has already confirmed the key is present and validates each entry itself.
     *
     * @param string $targetPath - Path of the config file to read; the caller has already confirmed the block is present.
     *
     * @return array<array-key, mixed> - Decoded YAML map of command to threshold; per-entry validation happens in the caller.
     * @throws ConfigException When the key is not a map shape.
     */
    private static function readMinimumSeverityBlock(string $targetPath): array
    {
        $decoded = Yaml::parseFile($targetPath);
        // Guard against the file changing under us since the probe: no map or no key means nothing to preserve.
        if (!is_array($decoded) || !array_key_exists('minimumSeverity', $decoded)) {
            return [];
        }

        $existing = $decoded['minimumSeverity'];
        // The block must be a keyed map; a bare list (e.g. `- advisory`) is a mistake worth telling the user about.
        if (!is_array($existing) || ($existing !== [] && array_is_list($existing))) {
            throw new ConfigException('Config key "minimumSeverity" must be a map of command name to threshold.');
        }

        return $existing;
    }

    /**
     * Confirms a preserved `minimumSeverity:` key names a command that actually gates (`analyse`,
     * `report`, `dashboard`), so init never carries a threshold for a command that would ignore it.
     *
     * @param mixed $command - Raw YAML map key; must be a string naming one of `ConfigLoader::GATING_COMMANDS`.
     *
     * @return string - Validated gating-command name, returned unchanged for use as the preserved map key.
     * @throws ConfigException When the key is not a string or names a non-gating command.
     */
    private static function validateGatingCommand(mixed $command): string
    {
        // YAML can yield a non-string key (e.g. a numeric map key); reject that before treating it as a command name.
        if (!is_string($command)) {
            throw new ConfigException('Config key "minimumSeverity" keys must be strings.');
        }

        // The key is a string but not a gating command; point the user at the valid names instead of silently keeping it.
        if (!in_array($command, ConfigLoader::GATING_COMMANDS, true)) {
            throw new ConfigException(sprintf(
                                          'Config key "minimumSeverity.%s" is not a valid gating command. Valid keys are: %s.',
                                          $command,
                                          implode(', ', ConfigLoader::GATING_COMMANDS),
                                      ));
        }

        return $command;
    }

    /**
     * Confirms a preserved threshold is one of the canonical `FailThreshold` values, so init never
     * carries forward a level (`advisory`, `warning`, `error`, `none`) that later gating can't read.
     *
     * @param string $command   - Owning command name, used only to point the rejection message at the offending key.
     * @param mixed  $threshold - Raw YAML value; must be a string accepted by `FailThreshold::fromInput`.
     *
     * @return string - Validated threshold string (one of `advisory`, `warning`, `error`, `none`).
     * @throws ConfigException When the value is not a string or not in the canonical four.
     */
    private static function validateGatingThreshold(string $command, mixed $threshold): string
    {
        // Anything but one of the four known level names (a typo like `warn`, or a non-string) is rejected here.
        if (!is_string($threshold) || FailThreshold::fromInput($threshold) === null) {
            throw new ConfigException(sprintf(
                                          'Config key "minimumSeverity.%s" value "%s" is not a valid threshold. Accepted: %s.',
                                          $command,
                                          is_string($threshold) ? $threshold : get_debug_type($threshold),
                                          implode(', ', array_map(static fn(FailThreshold $case): string => $case->value, FailThreshold::cases())),
                                      ));
        }

        return $threshold;
    }

    /**
     * Guards a `--force` regeneration against quietly overwriting a deliberately pinned
     * `schemaVersion:`. The scaffold always writes the canonical value, so a set-but-different
     * version is treated as user intent worth confirming rather than steamrolling.
     *
     * @param string $targetPath - Path of the config file to inspect; a missing, unparseable, or unset `schemaVersion` is allowed.
     *
     * @return void - Nothing; returns quietly when the version is absent or already canonical, and throws otherwise.
     * @throws ConfigException When the existing schemaVersion is set but does not match the canonical value.
     */
    private static function existingSchemaVersion(string $targetPath): void
    {
        // No file yet, so there is no pinned version to protect; let the scaffold write the canonical one.
        if (!is_file($targetPath)) {
            return;
        }

        try {
            $decoded = Yaml::parseFile($targetPath);
        } catch (ParseException) {
            // Unparseable YAML has no readable version to honour; let init proceed and rewrite the file cleanly.
            return;
        }

        // The document has no `schemaVersion` of its own, so there is nothing the user pinned to preserve.
        if (!is_array($decoded) || !array_key_exists('schemaVersion', $decoded)) {
            return;
        }

        $existing = $decoded['schemaVersion'];
        // A blank or non-string version is not a deliberate pin; ignore it and let the canonical value be written.
        if (!is_string($existing) || $existing === '') {
            return;
        }

        // A real version that differs from the canonical one is a deliberate override; stop and ask the user to clear it.
        if ($existing !== ConfigLoader::SCHEMA_VERSION) {
            throw new ConfigException(sprintf(
                                          'Config key "schemaVersion" must be "%s". Got "%s". Remove the deliberate override before regenerating with --force.',
                                          ConfigLoader::SCHEMA_VERSION,
                                          $existing,
                                      ));
        }
    }

    /**
     * Reads an existing config's `paths.ignore` list so a `--force` rerun keeps the user's local
     * ignore policy instead of resetting it to the shipped defaults. Any malformed block is rejected
     * whole, since a partly-kept ignore list would be worse than cleanly falling back to defaults.
     *
     * @param string $targetPath - Path of the config file to read; any non-list or blank-entry ignore block is rejected wholesale.
     *
     * @return list<string>|null - Existing ignore paths; null when there's nothing safe to preserve, so the defaults are used.
     */
    private static function existingIgnoredPaths(string $targetPath): ?array
    {
        // First-time init has no prior file, so there is no local ignore policy to carry forward.
        if (!is_file($targetPath)) {
            return null;
        }

        try {
            $decoded = Yaml::parseFile($targetPath);
        } catch (ParseException) {
            // Broken YAML gives us nothing trustworthy to reuse; fall back to the default ignore list.
            return null;
        }

        // A scalar or empty document has no structure to read ignores from; use the defaults.
        if (!is_array($decoded)) {
            return null;
        }

        $paths = $decoded['paths'] ?? null;
        // No `paths:` map means the user never set ignores here; leave the defaults in place.
        if (!is_array($paths)) {
            return null;
        }

        $ignore = $paths['ignore'] ?? null;
        // The `ignore` entry must be a plain list; a map or a missing entry means there is nothing to preserve.
        if (!is_array($ignore) || !array_is_list($ignore)) {
            return null;
        }

        $ignoredPaths = [];
        // Copy each configured glob across, checking as we go that the list holds only real path strings.
        foreach ($ignore as $path) {
            // One blank or non-string entry taints the whole list, so discard it entirely and use the defaults.
            if (!is_string($path) || trim($path) === '') {
                return null;
            }

            $ignoredPaths[] = trim($path);
        }

        return $ignoredPaths;
    }

    /**
     * Turns one rule's registry defaults into the YAML entry a user sees under `rules:`, emitting
     * only the keys that rule actually defines so the generated file stays free of empty noise.
     *
     * @param RuleDefinition $ruleDefinition - Rule definition to serialise.
     *
     * @return array<string, mixed> - config entry carrying only the keys this rule defines defaults for; always has `enabled`, with
     *                       `threshold`/`severity`/`thresholds`/`options` present only when the rule sets them
     */
    private static function buildRuleEntry(RuleDefinition $ruleDefinition): array
    {
        $ruleEntry = ['enabled' => $ruleDefinition->isEnabledByDefault];

        // Emit the threshold/severity pair only for rules that gate on a numeric limit; others omit it.
        if ($ruleDefinition->severityThreshold instanceof SeverityThreshold) {
            $ruleEntry['threshold'] = $ruleDefinition->severityThreshold->threshold;
            $ruleEntry['severity']  = $ruleDefinition->severityThreshold->severity->value;
        }

        // Only rules with named thresholds (e.g. size bands) carry a `thresholds` map into the file.
        if ($ruleDefinition->defaultThresholds !== []) {
            $ruleEntry['thresholds'] = $ruleDefinition->defaultThresholds;
        }

        // Likewise, only surface an `options` block when the rule ships tunable options to show.
        if ($ruleDefinition->defaultOptions !== []) {
            $ruleEntry['options'] = $ruleDefinition->defaultOptions;
        }

        return $ruleEntry;
    }
}
