<?php

declare(strict_types=1);

namespace GruffPhp\Tests\Console;

use GruffPhp\Engine\Config\ConfigLoader;
use Symfony\Component\Process\Process;
use Symfony\Component\Yaml\Yaml;

/**
 * Covers the init CLI command: writes registry-default config, refuses to overwrite, and respects --force.
 */
final class InitCliTest extends CliTestCase
{
    /**
     * Default ignore paths generated by the init command.
     *
     * @var list<string>
     */
    private const DEFAULT_IGNORED_PATHS = [
        '.agents/**',
        '.antigravitycli/**',
        '.claude/**',
        '.codex/**',
        '.github/**',
        '.goat-flow/**',
        'history.json',
        'infection-report.json',
        'src/Vendor/**',
        'tests/Fixtures/**',
    ];

    /**
     * Verify init writes a default config file at the project root.
     *
     * @return void
     */
    public function testInitWritesDefaultConfigFile(): void
    {
        $project = $this->tempDir();

        try {
            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                   ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;
            self::assertFileExists($configPath);
            self::assertStringContainsString('Wrote ' . $configPath, $process->getOutput());
            self::assertStringContainsString('Next steps:', $process->getOutput());
            self::assertStringContainsString('gruff-php analyse --generate-baseline', $process->getOutput());
            self::assertStringContainsString('known debt', $process->getOutput());
            self::assertStringContainsString('gruff-php analyse --no-baseline', $process->getOutput());

            $decoded = $this->decodedConfig($configPath);
            $this->assertGeneratedConfigShape($decoded);
            $this->assertIgnoredPaths(self::DEFAULT_IGNORED_PATHS, $decoded);
            $this->assertCognitiveComplexityDefault($decoded);
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify init refuses to overwrite an existing config file.
     *
     * @return void
     */
    public function testInitRefusesToOverwriteExistingFile(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($configPath, "# existing\n");

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                   ], $project);
            $process->run();

            self::assertNotSame(0, $process->getExitCode());
            self::assertStringContainsString('already exists', $process->getErrorOutput() . $process->getOutput());
            self::assertSame("# existing\n", file_get_contents($configPath));
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force overwrites an existing config file.
     *
     * @return void
     */
    public function testInitForceOverwritesExistingFile(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($configPath, "# existing\n");

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--force',
                                   ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $contents = $this->configContents($configPath);
            self::assertStringStartsWith('# .gruff-php.yaml', $contents);
            self::assertStringNotContainsString('# existing', $contents);
            self::assertStringContainsString('known debt', $process->getOutput());
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify init refuses when a legacy .gruff.yaml exists without --force.
     *
     * @return void
     */
    public function testInitRefusesWhenLegacyConfigPresent(): void
    {
        $project    = $this->tempDir();
        $legacyPath = $project . '/' . ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($legacyPath, "# legacy\n");

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                   ], $project);
            $process->run();

            self::assertNotSame(0, $process->getExitCode());
            self::assertStringContainsString(
                ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE,
                $process->getErrorOutput() . $process->getOutput(),
            );
            self::assertSame("# legacy\n", file_get_contents($legacyPath));
            self::assertFileDoesNotExist($project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE);
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force writes the preferred config alongside an existing legacy file.
     *
     * @return void
     */
    public function testInitForceWritesAlongsideLegacyConfig(): void
    {
        $project    = $this->tempDir();
        $legacyPath = $project . '/' . ConfigLoader::LEGACY_DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($legacyPath, "# legacy\n");

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--force',
                                   ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());
            self::assertSame("# legacy\n", file_get_contents($legacyPath));
            self::assertFileExists($project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE);
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --project-root writes the config into the supplied directory, not CWD.
     *
     * @return void
     */
    public function testInitWritesToProjectRootOption(): void
    {
        $cwd     = $this->tempDir();
        $project = $this->tempDir();

        try {
            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--project-root',
                                       $project,
                                   ], $cwd);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());
            self::assertFileExists($project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE);
            self::assertFileDoesNotExist($cwd . '/' . ConfigLoader::DEFAULT_CONFIG_FILE);
        } finally {
            $this->removeDir($cwd);
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force preserves an existing path ignore list.
     *
     * @return void
     */
    public function testInitForcePreservesExistingPathIgnores(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            $this->writeConfigWithCustomPathIgnores($configPath);

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--force',
                                   ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $decoded = $this->decodedConfig($configPath);
            $this->assertIgnoredPaths(['custom/cache/**', '.local-agent/**'], $decoded);
            $this->assertCognitiveComplexityDefault($decoded);
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify the scaffold emits the canonical schemaVersion + binary-default minimumSeverity block.
     *
     * @return void
     */
    public function testInitEmitsSchemaVersionAndMinimumSeverityBlock(): void
    {
        $project = $this->tempDir();

        try {
            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                   ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;
            $decoded    = $this->decodedConfig($configPath);

            self::assertSame('gruff-php.config.v0.1', $decoded['schemaVersion'] ?? null);
            self::assertSame(
                ['analyse' => 'advisory', 'report' => 'none', 'dashboard' => 'none'],
                $decoded['minimumSeverity'] ?? null,
            );
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force preserves a hand-edited minimumSeverity block byte-equivalent.
     *
     * @return void
     */
    public function testInitForcePreservesExistingMinimumSeverityBlock(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($configPath, implode("\n", [
                'schemaVersion: gruff-php.config.v0.1',
                'minimumSeverity:',
                '    analyse: error',
                '    report: warning',
                '    dashboard: warning',
                '',
            ]));

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--force',
                                   ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $decoded = $this->decodedConfig($configPath);
            self::assertSame(
                ['analyse' => 'error', 'report' => 'warning', 'dashboard' => 'warning'],
                $decoded['minimumSeverity'] ?? null,
            );
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force refuses to regenerate when the existing schemaVersion is a deliberate downgrade.
     *
     * @return void
     */
    public function testInitForceRejectsExistingDowngradedSchemaVersion(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($configPath, "schemaVersion: gruff-php.config.v0.0\n");

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--force',
                                   ], $project);
            $process->run();

            self::assertNotSame(0, $process->getExitCode());
            self::assertStringContainsString('schemaVersion', $process->getOutput() . $process->getErrorOutput());
            self::assertStringContainsString('gruff-php.config.v0.0', $process->getOutput() . $process->getErrorOutput());
            self::assertSame("schemaVersion: gruff-php.config.v0.0\n", file_get_contents($configPath));
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force rejects a hand-edited block that names a non-gating command.
     *
     * @return void
     */
    public function testInitForceRejectsExistingMinimumSeverityWithNonGatingCommand(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;
        $original   = "schemaVersion: gruff-php.config.v0.1\nminimumSeverity:\n    summary: error\n";

        try {
            file_put_contents($configPath, $original);

            $process = new Process([
                                       PHP_BINARY,
                                       self::PROJECT_ROOT . '/bin/gruff-php',
                                       'init',
                                       '--force',
                                   ], $project);
            $process->run();

            self::assertNotSame(0, $process->getExitCode());
            self::assertStringContainsString('minimumSeverity.summary', $process->getOutput() . $process->getErrorOutput());
            self::assertSame($original, file_get_contents($configPath));
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Write an existing config with local path-ignore policy.
     *
     * @param string $configPath - Destination the pre-existing config is written to before init runs.
     *
     * @return void
     */
    private function writeConfigWithCustomPathIgnores(string $configPath): void
    {
        file_put_contents($configPath, implode("\n", [
            'paths:',
            '    ignore:',
            "        - 'custom/cache/**'",
            "        - '.local-agent/**'",
            'rules:',
            '    size.file-length:',
            '        enabled: false',
            '',
        ]));
    }

    /**
     * Decode generated YAML config for assertions.
     *
     * @param string $configPath - Path of the config init generated, read back for assertions.
     *
     * @return array<string, mixed> - parsed config narrowed to string keys; values stay mixed for structural assertions
     */
    private function decodedConfig(string $configPath): array
    {
        $contents = $this->configContents($configPath);
        self::assertStringStartsWith('# .gruff-php.yaml', $contents);
        self::assertStringContainsString('paths.ignore', $contents);
        self::assertStringContainsString('gruff-php analyse --generate-baseline', $contents);

        $decoded = Yaml::parse($contents);

        return $this->stringKeyedArray($decoded);
    }

    /**
     * Assert the top-level generated config sections exist.
     *
     * @param array<string, mixed> $decoded - Parsed config payload.
     *
     * @return void
     */
    private function assertGeneratedConfigShape(array $decoded): void
    {
        self::assertArrayHasKey('schemaVersion', $decoded);
        self::assertArrayHasKey('minimumPhpVersion', $decoded);
        self::assertArrayHasKey('minimumSeverity', $decoded);
        self::assertArrayHasKey('paths', $decoded);
        self::assertArrayHasKey('allowlists', $decoded);
        self::assertArrayHasKey('selection', $decoded);
        self::assertArrayHasKey('rules', $decoded);
    }

    /**
     * Assert configured path ignores match the expected list.
     *
     * @param list<string>         $expectedPaths - Expected ignored paths.
     * @param array<string, mixed> $decoded - Parsed config payload.
     *
     * @return void
     */
    private function assertIgnoredPaths(array $expectedPaths, array $decoded): void
    {
        $paths = $this->stringKeyedArray($decoded['paths'] ?? null);
        self::assertSame($expectedPaths, $paths['ignore'] ?? null);
    }

    /**
     * Assert one representative registry default is emitted.
     *
     * @param array<string, mixed> $decoded - Parsed config payload.
     *
     * @return void
     */
    private function assertCognitiveComplexityDefault(array $decoded): void
    {
        $rules = $this->stringKeyedArray($decoded['rules'] ?? null);
        self::assertArrayHasKey('complexity.cognitive', $rules);
        self::assertSame(
            ['enabled' => true, 'threshold' => 20, 'severity' => 'error'],
            $rules['complexity.cognitive'],
        );
    }

    /**
     * Assert a decoded YAML value is an array keyed by strings.
     *
     * @param mixed $decodedValue - Raw YAML decode result asserted to be a string-keyed array.
     *
     * @return array<string, mixed> - the same entries re-typed as a string-keyed array once every key is verified to be a string
     */
    private function stringKeyedArray(mixed $decodedValue): array
    {
        self::assertIsArray($decodedValue);

        $result = [];
        foreach ($decodedValue as $key => $entry) {
            self::assertIsString($key);
            $result[$key] = $entry;
        }

        return $result;
    }

    /**
     * Read generated config file contents for assertions.
     *
     * @param string $configPath - Generated config file path.
     *
     * @return string - raw file text, asserted non-null first so callers can match against it directly
     */
    private function configContents(string $configPath): string
    {
        $contents = file_get_contents($configPath);
        self::assertIsString($contents);

        return $contents;
    }
}
