<?php

declare(strict_types=1);

namespace GruffPhp\Tests\Console;

use GruffPhp\Config\ConfigLoader;
use Symfony\Component\Process\Process;
use Symfony\Component\Yaml\Yaml;

/**
 * Covers the init CLI command: writes registry-default config, refuses to overwrite, and respects --force.
 */
final class InitCliTest extends CliTestCase
{
    /**
     * Default ignore paths generated by the init command.
     *
     * @var list<string>
     */
    private const DEFAULT_IGNORED_PATHS = [
        '.agents/**',
        '.antigravitycli/**',
        '.claude/**',
        '.codex/**',
        '.github/**',
        '.goat-flow/**',
        'history.json',
        'infection-report.json',
        'src/Vendor/**',
        'tests/Fixtures/**',
    ];

    /**
     * Verify init writes a default config file at the project root.
     *
     * @return void
     */
    public function testInitWritesDefaultConfigFile(): void
    {
        $project = $this->tempDir();

        try {
            $process = new Process([
                PHP_BINARY,
                self::PROJECT_ROOT . '/bin/gruff-php',
                'init',
            ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;
            self::assertFileExists($configPath);
            self::assertStringContainsString('Wrote ' . $configPath, $process->getOutput());
            self::assertStringContainsString('Next steps:', $process->getOutput());
            self::assertStringContainsString('gruff-php analyse --generate-baseline', $process->getOutput());
            self::assertStringContainsString('known debt', $process->getOutput());
            self::assertStringContainsString('gruff-php analyse --no-baseline', $process->getOutput());

            $decoded = $this->decodedConfig($configPath);
            $this->assertGeneratedConfigShape($decoded);
            $this->assertIgnoredPaths(self::DEFAULT_IGNORED_PATHS, $decoded);
            $this->assertCognitiveComplexityDefault($decoded);
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify init refuses to overwrite an existing config file.
     *
     * @return void
     */
    public function testInitRefusesToOverwriteExistingFile(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($configPath, "# existing\n");

            $process = new Process([
                PHP_BINARY,
                self::PROJECT_ROOT . '/bin/gruff-php',
                'init',
            ], $project);
            $process->run();

            self::assertNotSame(0, $process->getExitCode());
            self::assertStringContainsString('already exists', $process->getErrorOutput() . $process->getOutput());
            self::assertSame("# existing\n", file_get_contents($configPath));
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force overwrites an existing config file.
     *
     * @return void
     */
    public function testInitForceOverwritesExistingFile(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            file_put_contents($configPath, "# existing\n");

            $process = new Process([
                PHP_BINARY,
                self::PROJECT_ROOT . '/bin/gruff-php',
                'init',
                '--force',
            ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $contents = $this->configContents($configPath);
            self::assertStringStartsWith('# .gruff-php.yaml', $contents);
            self::assertStringNotContainsString('# existing', $contents);
            self::assertStringContainsString('known debt', $process->getOutput());
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Verify --force preserves an existing path ignore list.
     *
     * @return void
     */
    public function testInitForcePreservesExistingPathIgnores(): void
    {
        $project    = $this->tempDir();
        $configPath = $project . '/' . ConfigLoader::DEFAULT_CONFIG_FILE;

        try {
            $this->writeConfigWithCustomPathIgnores($configPath);

            $process = new Process([
                PHP_BINARY,
                self::PROJECT_ROOT . '/bin/gruff-php',
                'init',
                '--force',
            ], $project);
            $process->run();

            self::assertSame(0, $process->getExitCode(), $process->getErrorOutput());

            $decoded = $this->decodedConfig($configPath);
            $this->assertIgnoredPaths(['custom/cache/**', '.local-agent/**'], $decoded);
            $this->assertCognitiveComplexityDefault($decoded);
        } finally {
            $this->removeDir($project);
        }
    }

    /**
     * Write an existing config with local path-ignore policy.
     *
     * @return void
     */
    private function writeConfigWithCustomPathIgnores(string $configPath): void
    {
        file_put_contents($configPath, implode("\n", [
            'paths:',
            '    ignore:',
            "        - 'custom/cache/**'",
            "        - '.local-agent/**'",
            'rules:',
            '    size.file-length:',
            '        enabled: false',
            '',
        ]));
    }

    /**
     * Decode generated YAML config for assertions.
     *
     * @return array<string, mixed>
     */
    private function decodedConfig(string $configPath): array
    {
        $contents = $this->configContents($configPath);
        self::assertStringStartsWith('# .gruff-php.yaml', $contents);
        self::assertStringContainsString('paths.ignore', $contents);
        self::assertStringContainsString('gruff-php analyse --generate-baseline', $contents);

        $decoded = Yaml::parse($contents);

        return $this->stringKeyedArray($decoded);
    }

    /**
     * Assert the top-level generated config sections exist.
     *
     * @param array<string, mixed> $decoded Parsed config payload.
     * @return void
     */
    private function assertGeneratedConfigShape(array $decoded): void
    {
        self::assertArrayHasKey('minimumPhpVersion', $decoded);
        self::assertArrayHasKey('paths', $decoded);
        self::assertArrayHasKey('allowlists', $decoded);
        self::assertArrayHasKey('selection', $decoded);
        self::assertArrayHasKey('rules', $decoded);
    }

    /**
     * Assert configured path ignores match the expected list.
     *
     * @param list<string>         $expectedPaths Expected ignored paths.
     * @param array<string, mixed> $decoded       Parsed config payload.
     * @return void
     */
    private function assertIgnoredPaths(array $expectedPaths, array $decoded): void
    {
        $paths = $this->stringKeyedArray($decoded['paths'] ?? null);
        self::assertSame($expectedPaths, $paths['ignore'] ?? null);
    }

    /**
     * Assert one representative registry default is emitted.
     *
     * @param array<string, mixed> $decoded Parsed config payload.
     * @return void
     */
    private function assertCognitiveComplexityDefault(array $decoded): void
    {
        $rules = $this->stringKeyedArray($decoded['rules'] ?? null);
        self::assertArrayHasKey('complexity.cognitive', $rules);
        self::assertSame(
            ['enabled' => true, 'threshold' => 30, 'severity' => 'error'],
            $rules['complexity.cognitive'],
        );
    }

    /**
     * Assert a decoded YAML value is an array keyed by strings.
     *
     * @return array<string, mixed>
     */
    private function stringKeyedArray(mixed $decodedValue): array
    {
        self::assertIsArray($decodedValue);

        $result = [];
        foreach ($decodedValue as $key => $entry) {
            self::assertIsString($key);
            $result[$key] = $entry;
        }

        return $result;
    }

    /**
     * Read generated config file contents for assertions.
     *
     * @param string $configPath Generated config file path.
     * @return string Generated config file contents.
     */
    private function configContents(string $configPath): string
    {
        $contents = file_get_contents($configPath);
        self::assertIsString($contents);

        return $contents;
    }
}
